---
title: "Week 3 Assignment"
date: "September 21, 2019"
output: ioslides_presentation
---
## Interactive Scatterplot with Plotly


```{r setup, echo = FALSE, message=FALSE}
library(plotly); library(datasets); library(dplyr)

data <- data.frame(state.x77) %>% 
        mutate(region = state.region,
               abb = state.abb,
               name = state.name,
               division = state.division)
```

```{r plot, echo = FALSE, warning=FALSE}
plot_ly(data, x = ~HS.Grad, 
        y = ~Life.Exp, 
        type = "scatter", mode = "markers", 
        size = ~Population, color = ~region,
        text = ~name)  %>% 
        layout(title = "High School Graduation Rate vs. Life Expectancy")
```

## Code 

```{r code, echo = TRUE, eval = FALSE}

library(plotly); library(datasets); library(dplyr)

data <- data.frame(state.x77) %>% 
        mutate(region = state.region,
               abb = state.abb,
               name = state.name,
               division = state.division)

plot_ly(data, x = ~HS.Grad, 
   y = ~Life.Exp, 
   type = "scatter",mode = "markers", 
   size = ~Population, color = ~region,
   text = ~name)  %>% 
   layout(title = "High School Graduation Rate vs. Life Expectancy")
```

